######################################################################
# Automatically generated by qmake (3.0) Sun Dec 13 06:10:38 2015
######################################################################

TEMPLATE = app
TARGET = qt
INCLUDEPATH += .
@DEFINES += CORE_LIBRARY@
CONFIG+=debug
QMAKE_CXXFLAGS += -std=c++11

# Input
QT += core widgets
HEADERS += \ appgui.h
SOURCES += appgui.cpp get_token.cpp
